Fix route names and POST logic per suggestion from PaulYuk
Azure-Samples/functions-quickstart-powershell-azd pull request #3
Opened 2024-08-27 03:27 UTC by ggailey777

## Purpose

* Added a route to bring the endpoint URLs in line with the other lang samples.
* Updated the POST method to also expect `age`.
* Updated test files

## Does this introduce a breaking change?

```
[X] Yes (POST body has changed)
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[X] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Start the func.exe
* Run the POST using RESTClient.

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-08-27 20:30 UTC, ggailey777 commented
@paulyuk @bigmike @eamonoreilly

2024-08-27 20:45 UTC, paulyuk approved these changes
LGTM

2024-08-27 20:48 UTC, paulyuk requested changes
LGTM, small suggestion

2024-08-27 20:48 UTC, paulyuk commented on src/test.http
> +GET http://localhost:7071/api/httpget?name=Awesome%20Developer HTTP/1.1
```suggestion
GET http://localhost:7071/api/httpget?name=World HTTP/1.1
```

2024-09-23 21:18 UTC, BigMorty requested changes

2024-09-23 21:18 UTC, BigMorty commented on README.md
> +    azd init --template functions-quickstart-javascript-azd
```suggestion
    azd init --template functions-quickstart-powershell-azd
```

2024-09-24 17:07 UTC, ggailey777 commented on README.md
> +    azd init --template functions-quickstart-javascript-azd
Great catch on my `cut-and-paste` process 😉

2024-09-24 17:50 UTC, merged